/**
 * Utility functions package exports
 * Type guards and transformation utilities
 */

// Type guards
export {
  isString,
  isNumber,
  isBoolean,
  isObject,
  isArray,
  isFunction,
  isDefined,
  isNull,
  isUndefined,
  isSnowflake,
  isUserId,
  isGuildId,
  isChannelId,
  isMessageId,
  isBotToken,
  isUser,
  isGuild,
  isChannel,
  isMessage,
  isGuildMember,
  isRole,
  isEmoji,
  isArrayOf,
  isUserArray,
  isGuildArray,
  isChannelArray,
  isMessageArray,
  isRoleArray,
  isOneOf,
  hasProperty,
  hasRequiredProperties,
  isError,
  isErrorWithCode,
  isErrorWithStatus,
  isPromise,
  isPromiseLike,
  isAsyncIterable,
  isIterable,
} from './guards.js';

// Transformers
export {
  snowflakeToTimestamp,
  snowflakeToDate,
  snowflakeToWorkerId,
  snowflakeToProcessId,
  snowflakeToIncrement,
  iso8601ToUnix,
  unixToIso8601,
  unixToDate,
  dateToUnix,
  dateToIso8601,
  permissionsToArray,
  arrayToPermissions,
  hexToDecimal,
  decimalToHex,
  rgbToDecimal,
  decimalToRgb,
  buildAvatarUrl,
  buildGuildIconUrl,
  buildEmojiUrl,
  deepClone,
  snakeToCamel,
  camelToSnake,
} from './transformers.js';